Unit/Rarity Class実装に伴い、コード全体の修正対応
MasahiroKitaguchi/1226-ggg pull request #2
Opened 2019-01-20 09:16 UTC by MasahiroKitaguchi

## 概要
前回のレビュー内容から、Unit/Rarity Class を作成後、データ定義ファイル（data.php）を追加しています。
また、Unit/Rarity Classの親ファイルとしてinformation Classを作成しました。
gacha.phpならびにchoose.phpは削除しました。

### index.php
他ファイルの変更に伴い、若干の変更を行いました。
$unit_array->SelectUnitにレア度の情報と回数を渡し、抽選しています。

### unit.php / rarity.php
$units / $rarity に関するファイル

### raritycollection.php
抽選機能を実装しました。
LotteryMultiRare関数はレア度の抽選関数LotteryRare()を指定回数実行し、その結果をArrayに保存するものです

### unitcollection.php
SelectUnit関数は、LotteryMultiRare関数の結果をfilter_unit関数に渡し、レア度で絞り込みを行なった中からrandsでユニットのランダム抽選を行なっています。

### data.php
各データの定義を行なっています。

2019-01-21 10:48 UTC, hatajoe requested changes
@MasahiroKitaguchi レビューしました。

2019-01-21 10:48 UTC, hatajoe commented on unit.php
> +        $this->id = $id;
parent::__construct にてベースクラスのパラメータはセットされているのでここでは不要ですね。

2019-01-21 10:48 UTC, hatajoe commented on unitcollection.php
> +    public function SelectUnit(RarityCollection $rarities, int $num)
プロジェクトのメソッド名はキャメルケース、スネークケースのどちらかに統一した方が良いですね。
psr に準拠するなら メソッドや関数は camelCase です。

2019-01-21 10:48 UTC, hatajoe commented on unitcollection.php
> +        $this->unites = $unites;
unites → units ですね。

2019-01-21 10:48 UTC, hatajoe commented on data.php
> +$unit_array = new UnitCollection($unites);
$rarities や $unit_array の初期化は index.php でやった方が良いですかね。
data.php を require すれば読み書き可能なただのグローバル変数になってしまうので。

2019-01-21 10:48 UTC, hatajoe commented on unitcollection.php
> +            $unit_rare = Self::filter_units($rares->get_rarity());
filter_units は他クラスから参照されないメソッドなので、 UnitCollectionクラスのprivateメソッドにしましょ。

2019-01-21 17:35 UTC, MasahiroKitaguchi commented on unitcollection.php
> +        $this->unites = $unites;
ここ、どちらかというとget_units()じゃなくて、get_unites()とすれば・・・
いやそもそも$unitesという表記が間違えで、$unit_arrayにしないと誤解を招く状態でしょうか・・・

2019-01-21 23:19 UTC, hatajoe commented on unitcollection.php
> +        $this->unites = $unites;
unites って unit の複数形としては間違ってないですか？unit_array でも悪くないと思いますが、型は宣言時に定義しているので変数名としては冗長かなと思います。

2019-01-22 16:57 UTC, MasahiroKitaguchi commented on unitcollection.php
> +        $this->unites = $unites;
なるほど、２重の意味で勘違いをしてました。

2019-01-22 17:32 UTC, MasahiroKitaguchi commented on unitcollection.php
> +    public function SelectUnit(RarityCollection $rarities, int $num)
ローワーキャメルケースで統一しました

2019-01-22 17:33 UTC, MasahiroKitaguchi commented on unit.php
> +        $this->id = $id;
parent::__constructを追加した時に、削除し忘れてたので削除しました

2019-01-22 18:00 UTC, MasahiroKitaguchi commented
同じ手順でやったのですが、、、
git add <filename>
git commit -a -m "comment"
をしたら指定したファイルだけではなく全てのファイルが反映されちゃいました・・・

2019-01-25 03:45 UTC, hatajoe commented
@MasahiroKitaguchi commit コマンドに `-a` オプションを付けるとそういう挙動になっちゃいます。
コミットしたけど間違えちゃった、という時には `git reset HEAD^` というコマンドにて、そのコミットにてコミットした差分を手元に残したままリポジトリの状態を１つ前のコミットに戻せます。
あるいは、コミットメッセージを直したい、という場合は `git commit --amend` を実行すると、現在のコミットのコミットメッセージを編集できます。

2019-01-25 03:47 UTC, hatajoe commented
@MasahiroKitaguchi とりあえず、マージしますか

2019-01-25 19:06 UTC, merged

2019-01-25 19:06 UTC, MasahiroKitaguchi commented
I did